#spring.datasource.url=jdbc:mysql://localhost:3306/diary?useSSL=false&serverTimezone=UTC
#spring.datasource.username=diaryuser
#spring.datasource.password=1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: diaryuser
    password: 1234


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Diary
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8080



jwt:
  auth:
    converter:
      resource-id: diary-rest-api
      principle-attribute: preferred_username